version: "3.9"

services:
  indexer_ethereum_mainnet:
    build: .
    container_name: "indexer-ethereum-mainnet"
    restart: unless-stopped
    environment:
      RUST_BACKTRACE: "full"
      RUST_LOG: "eth_prototype=info"
      NETWORK: "ethereum_mainnet"
    volumes:
      - ./config.toml:/config.toml
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: "postgres:latest"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wow
      POSTGRES_DB: blockchains
    # ¡IMPORTANT! If you don't want to lose your data you should uncomment this
    # volumes:
    #   - ./data/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5