name: Security audit

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.cargo/audit.toml'
      - '.github/workflows/audit.yml'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo install cargo-audit --locked
      - name: Scan for vulnerabilities
        run: cargo audit
