name: Run tests

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v3
      - name: Enforce formatting
        run: cargo fmt --check

  test:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: wow
          POSTGRES_DB: blockchains
        ports:
          - 5432:5432
    steps:
    - name: Checkout Repo 
      uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose